// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/wukong-app/ruyi/internal/engine"
	"github.com/wukong-app/ruyi/internal/register"
	"github.com/wukong-app/ruyi/pkg/contract"
)

// Injectors from factory.go:

// New returns a new Ruyi.
func New() (contract.Ruyi, error) {
	converterRegistry, err := register.NewConverterRegistry()
	if err != nil {
		return nil, err
	}
	ruyi := engine.NewRuyi(converterRegistry)
	return ruyi, nil
}
